In [1]:
import sys
sys.path.insert(0, '../..')

In [2]:
%load_ext autoreload
%autoreload 2
import numpy as np
import edunn as nn
from edunn import utils

# Capa Flatten

La operación de aplanamiento (Flatten) en una red neuronal convolucional es bastante sencilla. En el método `forward`, simplemente necesitas cambiar la forma del tensor de entrada a un vector, respetando la dimensión de lotes. En el método `backward`, necesitas cambiar la forma del vector de nuevo a la forma original del tensor de entrada. Implementa ambos métodos.

In [3]:
np.random.seed(123)

x = np.random.rand(2,3,5,5)

layer=nn.Flatten()
y=layer.forward(x)

In [4]:
# Define el gradiente de la salida
g = np.random.rand(*y.shape)

# Propaga el gradiente hacia atrás a través de la convolución
layer_grad = layer.backward(g)
layer_grad

(array([[[[0.16593788, 0.78099794, 0.28653662, 0.30646975, 0.66526147],
          [0.11139217, 0.66487245, 0.88785679, 0.69631127, 0.44032788],
          [0.43821438, 0.7650961 , 0.565642  , 0.08490416, 0.58267109],
          [0.8148437 , 0.33706638, 0.92757658, 0.750717  , 0.57406383],
          [0.75164399, 0.07914896, 0.85938908, 0.82150411, 0.90987166]],
 
         [[0.1286312 , 0.08178009, 0.13841557, 0.39937871, 0.42430686],
          [0.56221838, 0.12224355, 0.2013995 , 0.81164435, 0.46798757],
          [0.80793821, 0.00742638, 0.55159273, 0.93193215, 0.58217546],
          [0.20609573, 0.71775756, 0.37898585, 0.66838395, 0.02931972],
          [0.63590036, 0.03219793, 0.74478066, 0.472913  , 0.12175436]],
 
         [[0.54263593, 0.06677444, 0.65336487, 0.99608633, 0.76939734],
          [0.57377411, 0.10263526, 0.69983407, 0.66116787, 0.04909713],
          [0.7922993 , 0.51871659, 0.42586769, 0.78818717, 0.41156922],
          [0.48102628, 0.18162884, 0.3213189 , 0.845533  ,

## Comprobaciones con PyTorch

In [5]:
import torch
import torch.nn as tnn

x = torch.from_numpy(x).to(torch.double)
x.requires_grad = True

flatten = tnn.Flatten()
y_torch = flatten(x)
y_torch

tensor([[0.6965, 0.2861, 0.2269, 0.5513, 0.7195, 0.4231, 0.9808, 0.6848, 0.4809,
         0.3921, 0.3432, 0.7290, 0.4386, 0.0597, 0.3980, 0.7380, 0.1825, 0.1755,
         0.5316, 0.5318, 0.6344, 0.8494, 0.7245, 0.6110, 0.7224, 0.3230, 0.3618,
         0.2283, 0.2937, 0.6310, 0.0921, 0.4337, 0.4309, 0.4937, 0.4258, 0.3123,
         0.4264, 0.8934, 0.9442, 0.5018, 0.6240, 0.1156, 0.3173, 0.4148, 0.8663,
         0.2505, 0.4830, 0.9856, 0.5195, 0.6129, 0.1206, 0.8263, 0.6031, 0.5451,
         0.3428, 0.3041, 0.4170, 0.6813, 0.8755, 0.5104, 0.6693, 0.5859, 0.6249,
         0.6747, 0.8423, 0.0832, 0.7637, 0.2437, 0.1942, 0.5725, 0.0957, 0.8853,
         0.6272, 0.7234, 0.0161],
        [0.5944, 0.5568, 0.1590, 0.1531, 0.6955, 0.3188, 0.6920, 0.5544, 0.3890,
         0.9251, 0.8417, 0.3574, 0.0436, 0.3048, 0.3982, 0.7050, 0.9954, 0.3559,
         0.7625, 0.5932, 0.6917, 0.1511, 0.3989, 0.2409, 0.3435, 0.5131, 0.6666,
         0.1059, 0.1309, 0.3220, 0.6616, 0.8465, 0.5533, 0.8545, 0.3848, 0.

In [6]:
utils.check_same(y_torch.detach().numpy(),y)

SUCCESS :) Arrays are equal (tolerance 1e-12)


In [7]:
# Define el gradiente de la salida
g = torch.from_numpy(g).to(torch.double)

# Propaga el gradiente hacia atrás a través de la convolución
y_torch.backward(g)

# Imprime el gradiente de la imagen de entrada
print("Gradiente de la entrada (δE/δx):")
print(x.grad, x.grad.shape)

Gradiente de la entrada (δE/δx):
tensor([[[[0.1659, 0.7810, 0.2865, 0.3065, 0.6653],
          [0.1114, 0.6649, 0.8879, 0.6963, 0.4403],
          [0.4382, 0.7651, 0.5656, 0.0849, 0.5827],
          [0.8148, 0.3371, 0.9276, 0.7507, 0.5741],
          [0.7516, 0.0791, 0.8594, 0.8215, 0.9099]],

         [[0.1286, 0.0818, 0.1384, 0.3994, 0.4243],
          [0.5622, 0.1222, 0.2014, 0.8116, 0.4680],
          [0.8079, 0.0074, 0.5516, 0.9319, 0.5822],
          [0.2061, 0.7178, 0.3790, 0.6684, 0.0293],
          [0.6359, 0.0322, 0.7448, 0.4729, 0.1218]],

         [[0.5426, 0.0668, 0.6534, 0.9961, 0.7694],
          [0.5738, 0.1026, 0.6998, 0.6612, 0.0491],
          [0.7923, 0.5187, 0.4259, 0.7882, 0.4116],
          [0.4810, 0.1816, 0.3213, 0.8455, 0.1869],
          [0.4173, 0.9890, 0.2366, 0.9168, 0.9184]]],


        [[[0.0913, 0.4637, 0.5022, 0.3137, 0.0473],
          [0.2417, 0.0955, 0.2382, 0.8078, 0.8950],
          [0.0432, 0.3019, 0.9806, 0.5395, 0.6263],
          [0.0055, 0.48

In [8]:
utils.check_same(x.grad.numpy(),layer_grad[0])

SUCCESS :) Arrays are equal (tolerance 1e-12)


In [9]:
samples = 100
batch_size=2
din=3 # dimensión de entrada
dout=5 # dimensión de salida
input_shape=(batch_size,din,3,3)

# Verificar las derivadas de un modelo de Flatten
# con valores aleatorios de `w`, `b`, y `x`, la entrada
layer=nn.Flatten()


utils.check_gradient.common_layer(layer,input_shape,samples=samples,tolerance=1e-5)    

Flatten_1 layer:
 ERROR 
δEδx
 Relative error (max):1.00000 (tolerance: 1e-05)
######################## Details: ######################## 
 Input x:
[[[[ 0.16054442  0.81976061  0.76505485]
   [-0.82898883 -0.65915131  0.61112355]
   [-0.14401335  1.3166056  -0.70434215]]

  [[ 0.75060992  0.34263798 -0.12643756]
   [ 1.17591077  0.68007153 -1.00496715]
   [ 0.64021868  1.37499063 -0.13044469]]

  [[-0.24865585 -0.66964715 -0.01360389]
   [ 0.68620069 -0.8176683  -1.34635756]
   [-0.37574991 -1.37972498  0.52321844]]]


 [[[-0.42668977 -1.75540184 -0.34860751]
   [-0.19261499  0.44913561 -0.14536354]
   [ 1.86872646 -0.51870385 -0.06239855]]

  [[-0.10291061 -0.28262838  0.14242559]
   [ 0.5412313   1.3400987  -1.56925613]
   [-0.51034287 -0.44777143  0.9378503 ]]

  [[-0.35666306 -1.89517559  0.08773046]
   [-0.03368923  0.17975157 -1.04016288]
   [ 1.71903468 -0.32385978 -0.18829686]]]]
 Input δEδy:
[[-0.90000857 -0.931002   -1.22273696 -0.39331085 -0.95758184  2.05646734
  -1.888492