In [1]:
import sys
sys.path.insert(0, '../..')

In [2]:
%load_ext autoreload
%autoreload 2
import numpy as np
import edunn as nn
from edunn import utils

# Capa Flatten

La operación de aplanamiento (Flatten) en una red neuronal convolucional es bastante sencilla. En el método `forward`, simplemente necesitas cambiar la forma del tensor de entrada a un vector, respetando la dimensión de lotes. En el método `backward`, necesitas cambiar la forma del vector de nuevo a la forma original del tensor de entrada. Implementa ambos métodos.

In [3]:
np.random.seed(123)

x = np.random.rand(2,3,5,5)

layer=nn.Flatten()
y=layer.forward(x)

In [4]:
# Define el gradiente de la salida
g = np.ones_like(y)

# Propaga el gradiente hacia atrás a través de la convolución
layer_grad = layer.backward(g)
layer_grad

(array([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]]),
 {})

# Comprobaciones con PyTorch

In [5]:
import torch
import torch.nn as tnn

x = torch.from_numpy(x).to(torch.double)
x.requires_grad = True

flatten = tnn.Flatten()
y_torch = flatten(x)
y_torch

tensor([[0.6965, 0.2861, 0.2269, 0.5513, 0.7195, 0.4231, 0.9808, 0.6848, 0.4809,
         0.3921, 0.3432, 0.7290, 0.4386, 0.0597, 0.3980, 0.7380, 0.1825, 0.1755,
         0.5316, 0.5318, 0.6344, 0.8494, 0.7245, 0.6110, 0.7224, 0.3230, 0.3618,
         0.2283, 0.2937, 0.6310, 0.0921, 0.4337, 0.4309, 0.4937, 0.4258, 0.3123,
         0.4264, 0.8934, 0.9442, 0.5018, 0.6240, 0.1156, 0.3173, 0.4148, 0.8663,
         0.2505, 0.4830, 0.9856, 0.5195, 0.6129, 0.1206, 0.8263, 0.6031, 0.5451,
         0.3428, 0.3041, 0.4170, 0.6813, 0.8755, 0.5104, 0.6693, 0.5859, 0.6249,
         0.6747, 0.8423, 0.0832, 0.7637, 0.2437, 0.1942, 0.5725, 0.0957, 0.8853,
         0.6272, 0.7234, 0.0161],
        [0.5944, 0.5568, 0.1590, 0.1531, 0.6955, 0.3188, 0.6920, 0.5544, 0.3890,
         0.9251, 0.8417, 0.3574, 0.0436, 0.3048, 0.3982, 0.7050, 0.9954, 0.3559,
         0.7625, 0.5932, 0.6917, 0.1511, 0.3989, 0.2409, 0.3435, 0.5131, 0.6666,
         0.1059, 0.1309, 0.3220, 0.6616, 0.8465, 0.5533, 0.8545, 0.3848, 0.

In [6]:
utils.check_same(y_torch.detach().numpy(),y)

SUCCESS :) Arrays are equal (tolerance 1e-12)


In [7]:
# Define el gradiente de la salida
g = torch.ones_like(y_torch)

# Propaga el gradiente hacia atrás a través de la convolución
y_torch.backward(g)

# Imprime el gradiente de la imagen de entrada
print("Gradiente de la entrada (δE/δx):")
print(x.grad, x.grad.shape)

Gradiente de la entrada (δE/δx):
tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 

In [8]:
utils.check_same(x.grad.numpy(),layer_grad[0])

SUCCESS :) Arrays are equal (tolerance 1e-12)


In [9]:
samples = 100
batch_size=2
din=3 # dimensión de entrada
dout=5 # dimensión de salida
input_shape=(batch_size,din,3,3)

# Verificar las derivadas de un modelo de Flatten
# con valores aleatorios de `w`, `b`, y `x`, la entrada
layer=nn.Flatten()


utils.check_gradient.common_layer(layer,input_shape,samples=samples,tolerance=1e-5)    

Flatten_1 layer:
 ERROR 
δEδx
 Relative error (max):1.00000 (tolerance: 1e-05)
######################## Details: ######################## 
 Input x:
[[[[ 1.39535293 -0.35893593 -0.54864213]
   [-2.5570546  -0.54892041 -0.97805771]
   [-0.35482446  0.39158424  0.17719233]]

  [[-0.02996801  0.19958211 -0.12611777]
   [ 0.19701893 -3.23105501 -0.26929349]
   [-0.11085072 -0.34126172 -0.21794626]]

  [[ 0.70331012 -0.59810533  2.2007021 ]
   [ 0.68829693 -0.00630725 -0.2066623 ]
   [-0.08652229 -0.91530707 -0.09520254]]]


 [[[ 0.27868352  0.57954162  0.57968978]
   [-0.27487755 -1.41608225 -0.66910263]
   [ 1.61219304  0.89605831  0.36961959]]

  [[-0.76129424  0.00364515 -1.25566869]
   [-0.55193688 -0.24520334 -0.36163993]
   [ 0.95660193 -1.41872591 -0.86543227]]

  [[-1.37468797 -1.23735321  0.1240559 ]
   [-1.60044053  0.75386878 -0.24681578]
   [ 0.06878833  0.32257674 -0.43416652]]]]
 Input δEδy:
[[ 1.03247972 -0.19434273  0.59407026 -0.19911238  0.29087439  0.27966267
   0.249969